#dnsmasq:
#    build: ./dnsmasq
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#    volumes:
#      - ~/opt:/opt
#    cap_add:
#      - "NET_ADMIN"

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      #- "dnsmasq"
      #- "gearman"
      - "mysql"
    volumes:
      - ~/opt:/opt
    dns:
        - "172.17.0.3"

nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"


#gearman:
#    build: ./gearman
#    ports:
#      - "4730:4730"
#    volumes:
#      - ~/opt:/opt
